<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-02-25 21:20

$extensionPath        = t3lib_extMgm::extPath('contexts_wurfl');
$extensionClassesPath = $extensionPath . 'Classes/';

return array(
	'tx_contexts_wurfl_context_type_wurfl'
		=> $extensionClassesPath . 'Context/Type/Wurfl.php',
);

?>
